### ISSUE TITLE
calicoctl fails to work when kernel has builtin ip6_tables

### ISSUE THREAD

**Issue by wtfbbqhax** [Metaswitch/calico-docker#150]
I use Linode VPS as my playground; running Ubuntu 15.04 x64. Linode builds the kernels with all things compiled in- e.g., ip6_tables is "builtin" in my case.

```
root at evilsec in ~ # ./calicoctl node --ip='173.255.224.31'
module ip6_tables isn't loaded. Load with `modprobe ip6_tables`
```

**Comment by tomdee** [comment]
Apologies for not responding sooner. Presumably this bug is stopping you from using calico? If so, we'll try to get a fix in the next release.

**Comment by wtfbbqhax** [comment]
Awesome, thanks!

**Comment by oscar-martin** [comment]
+1

**Comment by tomdee** [comment]
A fix has just gone into master for this. We'll hopefully do a release with it in on Monday.

**Comment by neiljerram** [comment]
Based on Alex Altair's release announcement (0.4.4), I'm concerned that this sounds like an incompatible change, but that you haven't announced it as such. 

If someone has a reproducible and reliable setup that boots a host and then executes a script including calicoctl commands, I believe that setup may now stop working - because those commands used to include the 'modprobe ip6_tables' step, but now an extra command is needed to do that. 

Am I right?

**Comment by spikecurtis** [comment]
@neiljerram I believe this change is back compatible.  In some very early versions of `calicoctl` we used to call `modprobe`.  More recently, we decided we didn't want `calicoctl` automatically loading kernel modules without asking the user.  

In recent versions `calicoctl` would check if the module was loaded and die if it wasn't.  The change we made just turns the error into a warning.

**Comment by neiljerram** [comment]
Ah, OK, that sounds fine then. Sorry for worrying!
