### ISSUE TITLE
Felix uses way too much CPU

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico-docker#3]
We've had reports that Felix can use easily a whole CPU core in this demo. Clearly this is being inflicted by the rapid poll rate in Felix for this demo (far higher than we use in any production environment), but we should determine whether or not this is the result of a bug or is expected behaviour.

**Comment by plwhite** [comment]
I think this should be an issue in the Felix repository - we know that shelling out is a CPU issue, and we should investigate how serious that issue is (which is quite easy to find out).

**Comment by Lukasa** [comment]
For now, until we've investigated whether this issue genuinely is going to get hit in any production environment, I think it should stay here. When we've concluded that it's a real problem we should open an issue to track the root cause on the Calico repo. =)

**Comment by plwhite** [comment]
I decided to investigate by removing the "ipset" commands from felix. The conclusion is that, on a single core and not incredibly fast VM with 4GB of RAM : 

* Removing all the ipset shelling out turned the CPU use from 13% to 6% (total,  over all processes, though Felix is the biggest share of that).
* Replacing all the ipset shelling out with shell calls to something else ("echo") to just measure the cost of a shell command left the CPU use at 13%.

Hence the cost of shelling out is about 7% of CPU (on this one box in this one case) - and since in the demo this is concentrated at short intervals, it's hardly surprising it's prohibitive.

I plan to turn this into a Felix issue.

**Comment by plwhite** [comment]
Closing this down as covered by Felix issue : https://github.com/Metaswitch/calico/issues/150
