### ISSUE TITLE
if the whole docker cluster is large enough, will the linux route table become a bottleneck?

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#62]
I notice that when launched a new container each host in the cluster will add a route rule, so if the cluster has 100 hosts, each host has 100 containers, the route table on each host will be more than 10000? will it become a bottleneck?

**Comment by Lukasa** [comment]
We don't believe so. We've done ad-hoc tests of the Linux kernel FIB at much larger scale than 10k and it has performed admirably.

In the event it does become problematic, it's not too difficult to perform aggregation on the routes if the IP address management system allows us to. That would involve essentially pre-allocating IP blocks to each host and then ensuring that containers launched on that host advertise only their aggregated route (e.g. one /24 instead of 256 /32s).

For the moment, however, we aren't concerned. =)
