### ISSUE TITLE
NAT rule for metadata address 169.254.169.254 should not be configured

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#90]
I found a NAT rule:

Chain felix-PREROUTING (1 references)
target     prot opt source               destination
DNAT       tcp  --  0.0.0.0/0            169.254.169.254      tcp dpt:80 to:127.0.0.1:8775

but i cannot connect to 169.254.169.254:80

**Comment by plwhite** [comment]
I think the answer to that is "no". That rule should only be created for an OpenStack deployment; with Docker it should be switched off (which can be done through the configuration).

For the short term it's harmless, but we ought to ensure that calico-docker sets the MetadataIP field to "NONE" to ensure that this rule is not populated. We'll address that in due course.

**Comment by lxpollitt** [comment]
Ideally I think there should be no orchestrator specific code in Felix, and that Felix should provide a generic API to the orchestrator plug-in (via our etcd data model) so that the plug-in can drive funnies like this OpenStack requirement themselves.  For most calico-docker deployments for example, we definitely don't want this NAT rule, but we may want to insert an SNAT rule to allow containers to reach out to the internet.  Obviously this ideal needs to be balanced against pragmatic requirements for 1.0 MVP, so I'm not making a hard push one way or the other.

**Comment by Symmetric** [comment]
Wort mentioning that other orchestrators use this IP too; e.g. CoreOS cloud
config.

I don't think this materially alters Alex's point, just wanted to flag it.

**Comment by robbrockbank** [comment]
MetadataAddr is now set to None in the calico-docker felix configuration ... verified that this is now fixed.
